---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - dotnet tool restore
      - dotnet GitVersion /output file /updateprojectfiles
      - cat GitVersion.json

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - dotnet test -c Release

#  - name: build
#    image: mcr.microsoft.com/dotnet/sdk:5.0
#    commands:
#      - dotnet build -c Release

trigger:
  event:
    - push

---
kind: pipeline
type: docker
name: tag

steps:
  - name: setup
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - dotnet tool restore
      - dotnet GitVersion /output file /updateprojectfiles
      - cat GitVersion.json

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - dotnet test -c Release

  - name: pack
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - dotnet pack -c Release

  - name: push
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - printenv | sort
      - |
        dotnet nuget add source \
          --username srohr-luther \
          --password $GITHUB_TOKEN \
          --store-password-in-clear-text \
          --name github "https://nuget.pkg.github.com/srohr-luther/index.json"
      - dotnet nuget push --skip-duplicate -s github src/bin/Release/*.nupkg
    environment:
      GITHUB_TOKEN:
        from_secret: github_token

trigger:
  branch:
    - master
  event:
    - tag
# ---
# kind: pipeline
# type: docker
# name: promote

# steps:
#   - name: publish
#     image: mcr.microsoft.com/dotnet/sdk:5.0
#     commands:
#       - dotnet tool restore
#       - dotnet publish -c Release
#   - name: push
#     image: alpine:latest
#     commands:
#       - ls -ahl src/bin/Release/net5.0/linux-x64/publish
#       - printenv | sort

# trigger:
#   event:
#     - promote

# ---
# kind: pipeline
# type: docker
# name: rollback

# steps:
#   - name: publish
#     image: mcr.microsoft.com/dotnet/sdk:5.0
#     commands:
#       - dotnet tool restore
#       - dotnet publish -c Release
#   - name: push
#     image: alpine:latest
#     commands:
#       - ls -ahl src/bin/Release/net5.0/linux-x64/publish
#       - printenv | sort

# trigger:
#   event:
#     - rollback
