---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - dotnet tool restore
      - dotnet GitVersion /output file /updateprojectfiles
      - cat GitVersion.json

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - dotnet test -c Release

#  - name: build
#    image: mcr.microsoft.com/dotnet/sdk:5.0
#    commands:
#      - dotnet build -c Release

trigger:
  event:
    - push

---
kind: pipeline
type: docker
name: tag

steps:
  - name: setup
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - dotnet tool restore
      - dotnet GitVersion /output file /updateprojectfiles
      - cat GitVersion.json

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - dotnet test -c Release

  - name: publish
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - dotnet publish -c Release

  - name: push
    image: alpine:latest
    commands:
      - ls -ahl src/bin/Release/net5.0/linux-x64/publish
      - printenv | sort

trigger:
  branch:
    - master
  event:
    - tag
# ---
# kind: pipeline
# type: docker
# name: promote

# steps:
#   - name: publish
#     image: mcr.microsoft.com/dotnet/sdk:5.0
#     commands:
#       - dotnet tool restore
#       - dotnet publish -c Release
#   - name: push
#     image: alpine:latest
#     commands:
#       - ls -ahl src/bin/Release/net5.0/linux-x64/publish
#       - printenv | sort

# trigger:
#   event:
#     - promote

# ---
# kind: pipeline
# type: docker
# name: rollback

# steps:
#   - name: publish
#     image: mcr.microsoft.com/dotnet/sdk:5.0
#     commands:
#       - dotnet tool restore
#       - dotnet publish -c Release
#   - name: push
#     image: alpine:latest
#     commands:
#       - ls -ahl src/bin/Release/net5.0/linux-x64/publish
#       - printenv | sort

# trigger:
#   event:
#     - rollback
